Metrics/LineLength:
  Max: 140

Style/FileName:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

AllCops:
  Exclude:
    - .kitchen/**/*
    - Guardfile
    - metadata.rb
    - spec/unit/test_spec.rb
    - vendor/**/*


