source 'https://rubygems.org'

gem 'rake'
gem 'foodcritic', '= 8.1.0'
gem 'rubocop', '= 0.39.0'
gem 'inspec', '= 1.4.0'
gem 'kitchen-inspec'
gem 'test-kitchen'
gem 'berkshelf', '~> 5.2.0'
gem 'stove'
